//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milservicios.Models.TablasSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANUNCIO()
        {
            this.CLASE_PART = new HashSet<CLASE_PART>();
            this.CUIDADO_MASC = new HashSet<CUIDADO_MASC>();
            this.CUIDADO_PERS = new HashSet<CUIDADO_PERS>();
            this.LABOR_DOM = new HashSet<LABOR_DOM>();
        }
    
        public int Id_Anuncio { get; set; }
        public int Duracion { get; set; }
        public string Horario { get; set; }
        public string Nacionalidad { get; set; }
        public bool Carnet { get; set; }
        public double Sueldo { get; set; }
        public string Zona { get; set; }
        public bool Fumador { get; set; }
        public Nullable<int> FAMILIA_Id_Usuario { get; set; }
        public Nullable<int> PROFESIONAL_Id_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASE_PART> CLASE_PART { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUIDADO_MASC> CUIDADO_MASC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUIDADO_PERS> CUIDADO_PERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LABOR_DOM> LABOR_DOM { get; set; }
    }
}
