//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milservicios.Models.TablasSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUIDADO_PERS
    {
        public int Id_Cuidado_Persona { get; set; }
        public short Edad { get; set; }
        public short Numero { get; set; }
        public string Tipo { get; set; }
        public int ANUNCIO_Id_Anuncio { get; set; }
    
        public virtual ANUNCIO ANUNCIO { get; set; }
    }
}
