//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milservicios.Models.TablasSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABOR_DOM
    {
        public int Id_Labor_Domestica { get; set; }
        public string Tarea { get; set; }
        public int ANUNCIO_Id_Anuncio { get; set; }
    
        public virtual ANUNCIO ANUNCIO { get; set; }
    }
}
